server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: postgres
    password: your_password

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379